version: "3.9"
services:
  db:
    image: "postgres:11-alpine"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    volumes:
      # Mount init scripts for postgres eg. create schema
      - ./taskmanager-service/src/main/resources/db/docker-init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"



